# Permalinks
permalink:        pretty

# Setup
title:            'PeterCoding'
tagline:          'A Personal Site'
description:      'Tech Explained'
url:              'https://petercoding.com'
baseurl:                  "/"
ads: ca-pub-8689548599050263

author:
  name:           'Peter Haddad'
  paginate:         5
  twitter:    'peter_haddad3'
  stackoverflow: '7015400'
  github: 'peterHdd'
  email: 'peterhd3412@gmail.com'

social:
  name: Peter Haddad
  links:
    - https://twitter.com/peter_haddad3
    - https://github.com/peterHdd
    - https://stackoverflow.com/users/7015400
 
# Custom vars
version:          3.8.3


plugins:  
    - jekyll-seo-tag
    - jekyll-sitemap

github:
  repo:           https://github.com/PeterHdd/peterhdd.github.io
analytics: UA-129540552-1