# Permalinks
permalink:        pretty

# Setup
name : Peter Coding
title:            'Peter Coding'
tagline:          'A Personal Site'
description:      'Tech Explained'
url:              'https://petercoding.com'
baseurl:                  "/"
ads: ca-pub-8689548599050263

author:
  name:           'Peter Haddad'
  paginate:         5
  twitter:    'peterndev'
  stackoverflow: '7015400'
  github: 'peterHdd'
  email: 'peterhd3412@gmail.com'

social:
  name: Peter Haddad
  links:
    - https://twitter.com/peterndev
    - https://github.com/peterHdd
    - https://stackoverflow.com/users/7015400
 
# Custom vars
version:          3.8.3


plugins:  
    - jekyll-seo-tag
    - jekyll-sitemap
    - jekyll-paginate

github:
  repo:           https://github.com/PeterHdd/peterhdd.github.io
analytics: UA-129540552-1

collections:
  category:
    output: true

defaults:
  -
    scope:
      path: ""
      type: category
    values:
      layout: "category"

## default date_format
date_format: 
  title: "%B-%-d-%Y"
  archive: "%b"
  categories: "%b-%Y"
  tag: "%b-%Y"
# Language
lan: "en" 

paginate: 10

highlighter: rouge
markdown: kramdown